ALTER TABLE "Plan" ADD COLUMN "validityDays" INTEGER;
ALTER TABLE "Plan" ADD COLUMN "emailCredits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "linkedInCredits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "mailboxLimit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "seatLimit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "emailCampaignLimit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "linkedInCampaignLimit" INTEGER NOT NULL DEFAULT 0;
