ALTER TABLE "Client" ADD COLUMN "emailCredits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Client" ADD COLUMN "mailboxLimit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Client" ADD COLUMN "emailCampaignLimit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LinkedInSubscription" ADD COLUMN "campaignLimit" INTEGER NOT NULL DEFAULT 0;
