/**
 * Working out what an inbound email actually is, and who it belongs to.
 *
 * Two things were wrong before this existed. An out-of-office counted as a real reply,
 * so the sequence stopped for someone who never read the mail. And a reply that arrived
 * from a different address than the one we wrote to ("info@" answering a mail sent to
 * "abc@") matched no contact at all, so it was neither counted nor allowed to stop the
 * follow-ups still going to the original address.
 */

/** Lower-cased header name → value, as read off the parsed message. */
export type HeaderMap = Record<string, string>;

const AUTO_SUBJECT =
  /(out of (the )?office|automatic reply|auto[\s-]?reply|autoreply|auto[\s-]?response|autoresponder|automatische antwort|réponse automatique|respuesta automática|on (annual )?leave|on vacation|away from (the )?office|maternity leave|currently unavailable)/i;

/**
 * Is this a machine-generated acknowledgement rather than a person answering?
 *
 * Header checks come from RFC 3834 and the conventions Exchange/Google actually send;
 * the subject check catches the rest, since plenty of auto-responders set no headers.
 */
export function isAutoReply(headers: HeaderMap, subject?: string): boolean {
  const h = (name: string) => (headers[name] ?? '').trim().toLowerCase();

  // RFC 3834: anything but "no" means it was generated by software.
  const autoSubmitted = h('auto-submitted');
  if (autoSubmitted && autoSubmitted !== 'no') return true;

  // Widely used vendor headers — presence alone is the signal.
  if (h('x-autoreply') || h('x-autorespond') || h('x-autoreply-from') || h('x-mail-autoreply')) return true;

  // Bulk/automated traffic: never a person replying to our mail.
  const precedence = h('precedence');
  if (['bulk', 'auto_reply', 'junk', 'list'].includes(precedence)) return true;

  // Exchange marks vacation messages this way.
  if (h('x-ms-exchange-inbox-rules-loop')) return true;

  return AUTO_SUBJECT.test(subject ?? '');
}

/** Message-IDs this email is answering, from In-Reply-To + References, without <>. */
export function threadRefs(inReplyTo?: string | null, references?: string | string[] | null): string[] {
  const raw: string[] = [];
  if (inReplyTo) raw.push(inReplyTo);
  if (Array.isArray(references)) raw.push(...references);
  else if (references) raw.push(...references.split(/\s+/));

  const out = new Set<string>();
  for (const r of raw) {
    for (const token of String(r).split(/\s+/)) {
      const id = token.trim().replace(/^<|>$/g, '');
      if (!id) continue;
      out.add(id);
      out.add(`<${id}>`); // stored ids may or may not keep the angle brackets
    }
  }
  return [...out];
}

/** The domain part of an address, lower-cased ('' when there isn't one). */
export function domainOf(email?: string | null): string {
  const at = (email ?? '').lastIndexOf('@');
  return at === -1 ? '' : email!.slice(at + 1).trim().toLowerCase();
}

/**
 * Consumer mailbox providers. A shared domain says nothing about who someone works for,
 * so "same domain" can only imply "same company" for everything except these.
 */
const FREE_DOMAINS = new Set([
  'gmail.com', 'googlemail.com', 'yahoo.com', 'yahoo.co.in', 'yahoo.co.uk', 'ymail.com',
  'hotmail.com', 'outlook.com', 'live.com', 'msn.com', 'aol.com', 'icloud.com', 'me.com',
  'protonmail.com', 'proton.me', 'gmx.com', 'gmx.de', 'mail.com', 'yandex.com', 'yandex.ru',
  'zoho.com', 'rediffmail.com', 'qq.com', '163.com', '126.com', 'naver.com', 'daum.net',
]);

export function isFreeMailDomain(domain: string): boolean {
  return FREE_DOMAINS.has((domain ?? '').toLowerCase());
}
